# Adapted from https://docs.modernleft.org/Docker-Images/bluesky-pds#traefik
# Traefik Proxy
services:
    traefik:
        image: traefik:v3.4.0
        hostname: example.com # the Traefik container should be reachable at the hostname so pdsadmin hits the Traefik container
        command:
            - --api.insecure=true
            - --providers.docker=true
            - --providers.docker.exposedbydefault=false
            - --entrypoints.http.address=:80
            - --entrypoints.https.address=:443
            - --certificatesresolvers.default.acme.tlschallenge=true
            - --certificatesresolvers.default.acme.email=admin@example.com
            - --certificatesresolvers.default.acme.storage=/certs/acme.json
            - --providers.file.directory=/certs
            - --providers.file.watch=true
            - --providers.file.filename=/certs/traefik-dynamic.yml
        ports:
            - "80:80"
            - "443:443"
            - "8080:8080" # Traefik dashboard
        networks:
            - proxy
        volumes:
            - /var/run/docker.sock:/var/run/docker.sock:ro
            - ./certs/traefik.crt:/certs/traefik.crt:ro
            - ./certs/traefik.key:/certs/traefik.key:ro
            - ./certs/traefik-dynamic.yml:/certs/traefik-dynamic.yml:ro

    bluesky-pds:
        image: code.modernleft.org/gravityfargo/bluesky-pds:v0.4.107
        networks:
            - proxy
        environment:
            # environment variables are passed in by the workflow
            PDS_ADMIN_PASSWORD: ${PDS_ADMIN_PASSWORD}
            PDS_JWT_SECRET: ${PDS_JWT_SECRET}
            PDS_PLC_ROTATION_KEY_K256_PRIVATE_KEY_HEX: ${PDS_PLC_ROTATION_KEY_K256_PRIVATE_KEY_HEX}
            PDS_HOSTNAME: ${PDS_HOSTNAME}
            # PDS_EMAIL_SMTP_URL:
            # PDS_EMAIL_FROM_ADDRESS:
            EUID: 1000
            EGID: 1000
        volumes:
            - ./bluesky-pds:/pds
            - ./certs/traefik.crt:/usr/local/share/ca-certificates/traefik.crt:ro
        labels:
            traefik.enable: "true"
            traefik.http.routers.bluesky-pds-insecure.entrypoints: http
            traefik.http.routers.bluesky-pds-insecure.rule: HostRegexp(`^.+\.example\.com$$`) || Host(`example.com`)
            traefik.http.routers.bluesky-pds-insecure.service: bluesky-pds
            # traefik.http.routers.bluesky-pds-insecure.middlewares: BlueskyHeaders@file
            traefik.http.routers.bluesky-pds-secure.entrypoints: https
            traefik.http.routers.bluesky-pds-secure.rule: HostRegexp(`^.+\.example\.com$$`) || Host(`example.com`)
            traefik.http.routers.bluesky-pds-secure.tls: "true"
            traefik.http.routers.bluesky-pds-secure.service: bluesky-pds
            traefik.http.services.bluesky-pds.loadbalancer.server.scheme: http
            traefik.http.services.bluesky-pds.loadbalancer.server.port: 3000
            # traefik.http.routers.bluesky-pds-secure.middlewares: BlueskyHeaders@file

networks:
    proxy:
        driver: bridge