name: Test Bluesky Provider

on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - main

jobs:
  test:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Set up Docker Compose
        run: sudo apt-get install -y docker-compose

      - name: Start services with remote Docker Compose
        run: |
          docker-compose -f https://github.com/bluesky-social/pds/raw/main/compose.yaml up -d
          CONTAINER_ID=$(docker-compose -f https://github.com/bluesky-social/pds/raw/main/compose.yaml ps -q bluesky-pds)
          echo "PDS_CONTAINER_ID=$CONTAINER_ID" >> $GITHUB_ENV

      - name: Show Bluesky PDS container logs
        run: |
          docker logs $PDS_CONTAINER_ID

      - name: Test PDS is healthy (from runner)
        run: |
          docker exec $PDS_CONTAINER_ID /bin/bash -c "curl -v https://caddy/xrpc/_health"
        continue-on-error: true

      - name: Test PDS is healthy (http:3000)
        run: |
          docker exec $PDS_CONTAINER_ID /bin/bash -c "curl -v http://localhost:3000/xrpc/_health"
        continue-on-error: true

      - name: Test Traefik is healthy (https)
        run: |
          docker exec $PDS_CONTAINER_ID /bin/bash -c "curl -v https://example.com/xrpc/_health"
        continue-on-error: true

      - name: Create admin account
        run: |
          docker exec $PDS_CONTAINER_ID /bin/bash -c "echo -e 'admin@example.com\nadminhandle' | sudo pdsadmin account create"

