name: Test Bluesky Provider

on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - main

jobs:
  test:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Set up OpenSSL
        run: sudo apt-get install -y openssl

      - name: Generate secrets
        run: |
          # Generate secret environment variables
          export PDS_ADMIN_PASSWORD=$(openssl rand --hex 16)
          export PDS_JWT_SECRET=$(openssl rand --hex 16)
          export PDS_PLC_ROTATION_KEY_K256_PRIVATE_KEY_HEX=$(openssl ecparam --name secp256k1 --genkey --noout --outform DER | tail --bytes=+8 | head --bytes=32 | xxd --plain --cols 32)

          echo "PDS_ADMIN_PASSWORD=${PDS_ADMIN_PASSWORD}" >> $GITHUB_ENV
          echo "PDS_JWT_SECRET=${PDS_JWT_SECRET}" >> $GITHUB_ENV
          echo "PDS_PLC_ROTATION_KEY_K256_PRIVATE_KEY_HEX=${PDS_PLC_ROTATION_KEY_K256_PRIVATE_KEY_HEX}" >> $GITHUB_ENV
          echo "PDS_HOSTNAME=localhost" >> $GITHUB_ENV

      - name: Pull the Bluesky PDS Docker container
        run: |
          docker pull \
            gravityfargo/bluesky-pds:v0.4.107

      - name: Write docker-compose.yml with Traefik # from https://docs.modernleft.org/Docker-Images/bluesky-pds#traefik
        run: |
          cat <<EOF > docker-compose.yml
version: "3.8"
services:
  bluesky-pds:
    image: code.modernleft.org/gravityfargo/bluesky-pds:v0.4.107
    networks:
      - proxy
    environment:
      PDS_JWT_SECRET: ${PDS_JWT_SECRET}
      PDS_ADMIN_PASSWORD: ${PDS_ADMIN_PASSWORD}
      PDS_PLC_ROTATION_KEY_K256_PRIVATE_KEY_HEX: ${PDS_PLC_ROTATION_KEY_K256_PRIVATE_KEY_HEX}
      PDS_HOSTNAME: localhost
      EUID: 1000
      EGID: 1000
    volumes:
      - ./bluesky-pds:/pds
    labels:
      traefik.enable: "true"
      traefik.http.routers.bluesky-pds-insecure.entrypoints: http
      traefik.http.routers.bluesky-pds-insecure.rule: HostRegexp(\`^.+\.localhost$\`) || Host(\`localhost\`)
      traefik.http.routers.bluesky-pds-secure.entrypoints: https
      traefik.http.routers.bluesky-pds-secure.rule: HostRegexp(\`^.+\.localhost$\`) || Host(\`localhost\`)
      traefik.http.routers.bluesky-pds-secure.tls: "true"
      traefik.http.services.bluesky-pds.loadbalancer.server.scheme: http
      traefik.http.services.bluesky-pds.loadbalancer.server.port: 3000
networks:
  proxy:
    driver: bridge
EOF

# CONTAINER_ID=$(docker run -d gravityfargo/bluesky-pds:v0.4.107)
      - name: Run Bluesky PDS Docker container
        run: |
          CONTAINER_ID=$(docker-compose up -d)
          echo "PDS_CONTAINER_ID=$CONTAINER_ID" >> $GITHUB_ENV

      - name: Create admin account
        run: |
          docker exec $PDS_CONTAINER_ID /bin/bash -c "echo -e 'admin@example.com\nadminhandle' | sudo pdsadmin account create"


      # - name: Wait for the container to be ready
      #   run: sleep 30

      # - name: Run Terraform Init
      #   run: |
      #     terraform init

      # - name: Run Terraform Apply
      #   run: |
      #     terraform apply -auto-approve

      # - name: Clean up
      #   run: |
      #     docker stop $(docker ps -q --filter ancestor=gravityfargo/bluesky-pds:latest)
      #     docker rm $(docker ps -aq --filter ancestor=gravityfargo/bluesky-pds:latest)