name: Test Bluesky Provider

on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - main

jobs:
  tf-test:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Download PDS installer.sh
        run: |
          curl https://raw.githubusercontent.com/bluesky-social/pds/main/installer.sh > installer.sh

      - name: Run installer.sh
        run: |
          echo -e 'example.com\nadmin@example.com' | sudo bash installer.sh

      - name: Wait for the container to be ready
        run: sleep 5

      - name: Show Bluesky PDS container logs
        run: |
          docker logs $PDS_CONTAINER_ID

      - name: Test PDS is healthy (from runner)
        run: |
          docker exec $PDS_CONTAINER_ID /bin/bash -c "curl -v https://caddy/xrpc/_health"
        continue-on-error: true

      - name: Test PDS is healthy (http:3000)
        run: |
          docker exec $PDS_CONTAINER_ID /bin/bash -c "curl -v http://localhost:3000/xrpc/_health"
        continue-on-error: true

      - name: Test Traefik is healthy (https)
        run: |
          docker exec $PDS_CONTAINER_ID /bin/bash -c "curl -v https://example.com/xrpc/_health"
        continue-on-error: true

      - name: Create admin account
        run: |
          docker exec $PDS_CONTAINER_ID /bin/bash -c "echo -e 'admin@example.com\nadminhandle' | sudo pdsadmin account create"

